project:
  type: website
  output-dir: docs

website:
  title: "Medienbasierte Wissenskonstruktion mit R"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Kontakt"
        file: contact.qmd
      - text: "Nice to Know"
        file: ntn.qmd
  sidebar:
    logo: "assets/img/logo_ude.png"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Basics"
        contents:
          - installation.qmd
          - intro.qmd
      - section: "Data Wrangling & Visualisierung"
        contents:
          - datawrangling_base.qmd
          - datawrangling_dplyr.qmd
          - dataviz_ggplot2.qmd
      - section: "Inferenzstatistik & Berichten"
        contents:
          - content3.qmd
          - quarto_reports.qmd
      - section: "Anwendung: Fragebögen I"
        contents:
          - analysis1.qmd
          - analysis2.qmd
          - analysis3.qmd
      - section: "Anwendung: Fragebögen II"
        contents: 
          - 5join.qmd
          - 5outlier.qmd
          - 5factorplot.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

