project:
  type: website

website:
  title: "Medienbasierte Wissenskonstruktion mit R"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Infos"
        file: index.qmd
      - text: "Kontakt"
        file: index.qmd
  sidebar:
    logo: "assets/img/logo_ude.png"
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - installation.qmd
      - section: "Data Wrangling & Visualisierung"
        contents:
          - datawrangling_base.qmd
          #- datawrangling_dplyr.qmd
          #- dataviz_ggplot2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

